tpz = tpz or {}
tpz.music = tpz.music or {}

------------------------------------
-- Music Type
------------------------------------
tpz.music.type =
{
    DAY             = 0,
    NIGHT           = 1,
    BATTLE_SOLO     = 2,
    BATTLE_PARTY    = 3,
    CHOCOBO         = 4
}

------------------------------------
-- Music Track
------------------------------------
-- Need to rename enum with list from https://www.bg-wiki.com/ffxi/Category:Music
tpz.music.track =
{
    NONE                       = 0,   -- Silence
    CLOISTER_OF_TIME_SOULS     = 40,  -- CS
    ROYAL_WANDERLUST           = 41,  -- Cait Sith Theme
    SNOWDRIFT_WALTZ            = 42,  -- Xarcabard [S]
    TROUBLED_SHADOWS           = 43,  -- Castle Zvahl Baileys [S]/Castle Zvahl Keep [S]
    WHERE_LORDS_RULE_NOT       = 44,  -- La Vaule [S]/Beadeaux [S]/Castle Oztroja [S]
    SUMMERS_LOST               = 45,  -- CS
    GODDESS_DIVINE             = 46,  -- WotG Final Battle
    ECHOES_OF_CREATION         = 47,  -- ACP Final Battle
    MAIN_THEME                 = 48,  -- CS
    LUCK_OF_THE_MOG            = 49,  -- AMK Final Battle
    FEAST_OF_THE_LADIES        = 50,  -- ASA Final Battle
    SCARLET_SKIES_SHADOWED_PLAINS = 51,  -- Abyssea
    MELODIES_ERRANT            = 52,  -- Battle (Abyssea zones)
    SHINRYU                    = 53,  -- Shinryu
    EVERLASTING_BONDS          = 54,  -- CS
    PROVENANCE_WATCHER         = 55,  -- Provenance Watcher Battle
    WHERE_IT_ALL_BEGINS        = 56,  -- Provenance
    STEEL_SINGS_BLADES_DANCE   = 57,  -- Battle (Seekers zones)
    A_NEW_DIRECTION            = 58,  -- Title Screen 5 (Seekers)
    THE_PIONEERS               = 59,  -- Western Adoulin
    INTO_LANDS_PRIMEVAL        = 60,  -- Yahse Hunting Grounds/Ceizak Battlegrounds/Foret de Hennetiel/Morimar Basalt Fields/Marjami Ravine
    WATERS_UMBRAL_KNELL        = 61,  -- Rala Waterways/Yorcia Weald
    KEEPERS_OF_THE_WILD        = 62,  -- Wildkeeper Reive, Seekers instances
    THE_SACRED_CITY_OF_ADOULIN = 63,  -- Eastern Adoulin/Celennia Memorial Library
    BREAKING_GROUND            = 64,  -- Colonization Reive
    HADES                      = 65,  -- CS
    ARCIELA                    = 66,  -- CS
    MOG_RESORT                 = 67,  -- Mog Garden
    WORLDS_AWAY                = 68,  -- CS
    MONSTROSITY                = 70,  -- Monstrosity
    THE_PIONEERS_PIANO         = 71,  -- CS
    THE_DIVINE                 = 72,  -- Kamihr Drifts
    THE_SERPENTINE_LABYRINTH   = 73,  -- Outer Ra'Kaznar
    CLOUDS_OVER_ULBUKA         = 74,  -- Balamor's theme song
    THE_PRICE                  = 75,  -- Adoulin Final Battle
    FOREVER_TODAY              = 76,  -- Adoulin Ending Song
    FOREVER_TODAY_INSTRUMENTAL = 78,  -- Instrumental
    ISLE_OF_THE_GODS           = 81,  -- Rhapsodies final boss
    WAIL_OF_THE_VOID           = 82,  -- Rhapsodies finale
    RHAPSODIES_OF_VANA_DIEL    = 83,  -- Ending Song
    UNKNOWN_NAME               = 84,  -- Mount riding music
    BATTLE_THEME               = 101, -- Battle (solo, outdoor, ) (COP solo battle music?)
    BATTLE_IN_THE_DUNGEON_2    = 102, -- Battle (party, dungeon, original zones)
    BATTLE_THEME_2             = 103, -- Battle (party, outdoor, ) (Original party music?)
    A_ROAD_ONCE_TRAVELLED      = 104, -- CS
    MHAURA                     = 105, -- Mhaura
    VOYAGER                    = 106, -- Boats to/from Selbina/Mhaura
    THE_KINGDOM_OF_SAN_DORIA   = 107, -- Southern San dOria/Northern San dOria/Port San dOria
    VAN_DIEL_MARCH             = 108, -- Title Screen 1 (Original+Zilart)
    RONFAURE                   = 109, -- East/West Ronfaure
    THE_GRAND_DUCHY_OF_JEUNO   = 110, -- Upper/Lower/Port Jeuno
    BLACKOUT                   = 111, -- Death
    SELBINA                    = 112, -- Selbina
    SARUTABARUTA               = 113, -- East/West Sarutabaruta
    BATALLIA                   = 114, -- Batallia Downs
    BATTLE_IN_THE_DUNGEON      = 115, -- Battle (solo, dungeon, original zones) (COP?)
    GUSTABERG                  = 116, -- North/South Gustaberg
    RELUDE_GARDENS             = 117, -- RuLude Gardens
    ROLANBERRY_FIELDS          = 118, -- Rolanberry Fields
    AWAKENING                  = 119, -- Dynamis-Xarcabard / Shadow Lord fight
    VANA_DIEL_MARCH_2          = 120, -- Nation Selection
    SHADOW_LORD                = 121, -- Dynamis-Valkurm/Buburimu/Qufim/Tavnazia/Beaucedine/San dOria/Bastok/Windurst/Jeuno/ (Shadow Lord Theme)
    ONE_LAST_TIME              = 122, -- CS
    HOPELESSNESS               = 123, -- CS
    RECOLLECTION               = 124, -- CS
    TOUGH_BATTLE               = 125, -- BCNM (original)
    MOG_HOUSE                  = 126, -- Mog House
    ANXIETY                    = 127, -- CS
    AIRSHIP                    = 128, -- Airship
    HOOK_LINE_AND_SINKER       = 129, -- Fishing 1
    TARUTARU_FEMALE            = 130, -- Character Creation - Taru Female
    ELVAAN_FEMALE              = 131, -- Character Creation - Elvaan Female
    ELVAAN_MALE                = 132, -- Character Creation - Elvaan Male
    HUME_MALE                  = 133, -- Character Creation - Hume Male
    YUHTUNGA_JUNGLE            = 134, -- Yuhtunga/Yhoator Jungle
    KAZHAM                     = 135, -- Kazham
    THE_BIG_ONE                = 136, -- Fishing 2
    A_REALM_OF_EMPTINESS       = 137, -- CoP Final Boss
    MERCENARIES_DELIGHT        = 138, -- Battle (party, Outdoor, Aht Urhgan Zones)
    DELVE                      = 139, -- Battle (party, indoor, Aht Urhgan Zones)
    WINGS_OF_THE_GODDESS       = 140, -- Title Screen 4 (WotG)
    THE_COSMIC_WHEEL           = 141, -- West Sarutabaruta [S]
    FATED_STRIFE               = 142, -- Besieged
    HELLRIDERS                 = 143, -- Einherjar
    RAPID_ONSLAUGHT            = 144, -- Assault
    ENCAMPMENT_DREAMS          = 145, -- CS
    THE_COLOSSEUM              = 146, -- Pankration
    EASTWARD_BOUND             = 147, -- Boats to/from Nashmau/Al Zahbi
    FORBIDDEN_SEAL             = 148, -- Nyzul Isle/Salvage
    JEWELED_BOUGHS             = 149, -- Wajaom Woodlands/Bhaflau Thickets
    ULULATIONS_FROM_BEYOND     = 150, -- Arrapago Reef
    THE_FEDERATION_OF_WINDURST = 151, -- Windurst Waters/Walls/Woods/Port
    THE_REPUBLIC_OF_BASTOK     = 152, -- Bastok Mines/Markets/Port
    PRELUDE                    = 153, -- CS
    METALWORKS                 = 154, -- Metalworks
    CASTLE_ZVAHL               = 155, -- Castle Zvahl Baileys/Castle Zvahl Keep/Throne Room
    CHATEAU_DORAGUILLE         = 156, -- Chateau dOraguille
    FURY                       = 157, -- CS
    SAUROMUGUE_CHAMPAIGN       = 158, -- Sauromugue Champaign
    SORROW                     = 159, -- CS
    REPRESSION_MEMORO          = 160, -- CS
    DESPAIR_MEMORO             = 161, -- CS
    HEAVENS_TOWER              = 162, -- Heavens Tower
    SOMETIME_SOMEWHERE         = 163, -- CS
    XARCABARD                  = 164,
    VICTORY_FANFARE            = 165, -- Victory
    THE_DARKNESS               = 166, -- CS
    THE_ANTIQUITYS_END         = 167, -- CS
    VICTORY                    = 168, -- Conquest results
    CASTLE_OZTROJA             = 169, -- Castle Oztroja
    TOWN                       = 170, -- CS
    CHOCOLLS_THEME             = 171, -- Riding a Chocobo
    THE_ICE_CAVERN             = 172, -- FeiYin
    EXPLORE                    = 173, -- RoMaeve
    TARUTARU_MALE              = 174, -- Character Creation - Taru Male
    THE_GRAND_DUKE_OF_JEUNO    = 175, -- Dynamis Lord (Boss)
    ELYVAN_FEMALE              = 176, -- Character Creation - Elyvan Female
    ELYVAN_MALE                = 177, -- Character Creation - Elyvan Male
    HUM_MALE                   = 178, -- Character Creation - Hume Male
    YUHTUNG_JUNGLE             = 179, -- Yuhtunga Jungle
    BATTLE_MUSIC               = 180, -- Battle (Outdoor, Zilart Zones)
    TOWN2                      = 181, -- CS
    SAN_DORIA                  = 182, -- San dOria
    BATTLE3                    = 183, -- Battle (Original Outdoor)
    BATTLE4                    = 184, -- BCNM (Original)
    MAIN_THEMES                = 185, -- CS
    MH                         = 186, -- MH
    PTY1                       = 187, -- Party Theme 1
    DUNGEON                    = 188, -- Original Dungeon
    DUNGEON2                   = 189, -- Original Dungeon 2
    TOWN3                      = 190, -- CS
    SANDORIA                   = 191, -- San dOria (Zilart party battle music?)
    BATTLE5                    = 192, -- Battle (Original Dungeon)
    TOWN4                      = 193, -- CS
    BATTLE6                    = 194, -- Battle (Original Dungeon)
    HUME_FEMALE                = 195, -- Character Creation - Hume Female
    GALKA                      = 196, -- Character Creation - Galka (Fighters of the crystal?)
    BATTLE7                    = 197, -- BCNM (Original) (Kamlanaut theme #2)
    PRELUDE2                   = 198, -- Prelude 2 (Eald'narche battle theme)
    PRELUDE3                   = 199, -- Prelude 3
    THE_SHATTERING             = 200, -- CS (Kamlanaut theme #1)
    FIELD_THEME                = 201, -- Outdoor Field Theme
    FORTRESS_THEME             = 202, -- Fortress Theme
    CASTLE_THEME               = 203, -- Castle Theme
    TAVNAZIA                   = 204, -- Lufaise Meadows/Tavnazian Safehold/Phomiuna Aqueducts/Sacrarium/Misareaux Coast/AlTaieu/Empyreal Paradox/Sealion Den
    CASTLE_THEME2              = 205, -- Castle Theme 2
    TOWN5                      = 206, -- CS
    BATTLE8                    = 207, -- Battle (Outdoor, Zilart)
    FINAL_BATTLE               = 208, -- Final Boss
    THE_FEDERATION_OF_WINDURST2 = 209, -- Windurst Waters [S]
    SEA                        = 210, -- AlTaieu/Empyreal Paradox
    CASTLE_THEME3              = 211, -- Castle Theme 3
    VICTORY_FANFARE2           = 212, -- Conquest Victory Fanfare 2
    TOWN6                      = 213, -- CS
    SAN_DORIA_CASTLE           = 214, -- Chateau dOraguille [S]
    CASTLE_THEME4              = 215, -- Castle Theme 4
    FINAL_BOSS                 = 216, -- CS
    CITY_OF_JEUNO              = 217, -- RuLude Gardens (Original Version)
    BLACKOUT2                  = 218, -- CS
    JUNGLE_THEME               = 219, -- Yhoator Jungle (COP party battle music?)
    FINAL_THEME                = 220, -- CS (CoP BCNM music)
    FINAL_BOSS2                = 221, -- Final Boss 2
    FINAL_BOSS3                = 222, -- Final Boss 3
    FINAL_BOSS4                = 223, -- Final Boss 4
    FINAL_BOSS5                = 224, -- Final Boss 5
    FINAL_BOSS6                = 225, -- Final Boss 6
    FINAL_BOSS7                = 226, -- Final Boss 7
    FINAL_BOSS8                = 227, -- Final Boss 8
    FINAL_BOSS9                = 228, -- Final Boss 9
    FINAL_BOSS10               = 229, -- Final Boss 10
    FINAL_BOSS11               = 230, -- Final Boss 11
    FINAL_BOSS12               = 231, -- Final Boss 12
    FINAL_BOSS13               = 232, -- Final Boss 13
    FINAL_BOSS14               = 233, -- Final Boss 14
    FINAL_BOSS15               = 234, -- Final Boss 15
    FINAL_BOSS16               = 235, -- Final Boss 16
    FINAL_BOSS17               = 236, -- Final Boss 17
    FINAL_BOSS18               = 237, -- Final Boss 18
    FINAL_BOSS19               = 238, -- Final Boss 19
    FINAL_BOSS20               = 239, -- Final Boss 20
    FINAL_BOSS21               = 240, -- Final Boss 21
    FINAL_BOSS22               = 241, -- Final Boss 22
    FINAL_BOSS23               = 242, -- Final Boss 23
    FINAL_BOSS24               = 243, -- Final Boss 24
    FINAL_BOSS25               = 244, -- Final Boss 25
    FINAL_BOSS26               = 245, -- Final Boss 26
    FINAL_BOSS27               = 246, -- Final Boss 27
    FINAL_BOSS28               = 247, -- Final Boss 28
    FINAL_BOSS29               = 248, -- Final Boss 29
    FINAL_BOSS30               = 249, -- Final Boss 30
    FINAL_BOSS31               = 250, -- Final Boss 31
    FINAL_BOSS32               = 251, -- Final Boss 32
    FINAL_BOSS33               = 252, -- Final Boss 33
    FINAL_BOSS34               = 253, -- Final Boss 34
    FINAL_BOSS35               = 254, -- Final Boss 35
    FINAL_BOSS36               = 255, -- Final Boss 36
    FINAL_BOSS37               = 256, -- Final Boss 37
    FINAL_BOSS38               = 257, -- Final Boss 38
    FINAL_BOSS39               = 258, -- Final Boss 39
    FINAL_BOSS40               = 259, -- Final Boss 40
}
