UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 200;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 201;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 202;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 270;
UPDATE tpzdb . mob_pools SET skill_list_id = 1163 WHERE familyid = 942;
UPDATE tpzdb . mob_pools SET skill_list_id = 1164  WHERE familyid = 943;
UPDATE tpzdb . mob_pools SET skill_list_id = 1165 WHERE familyid = 944;
UPDATE tpzdb . mob_pools SET cmbDelay = 120 WHERE familyid = 131;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 203;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 204;
UPDATE tpzdb . mob_pools SET cmbDelay = 260 WHERE familyid = 205;
UPDATE tpzdb . mob_pools SET cmbDelay = 290 WHERE familyid = 251;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 246;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 326;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 923;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 246;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 326;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 923;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 218;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 218;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 219;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 219;
UPDATE tpzdb . mob_pools SET mJob = 1 WHERE familyid = 551;
UPDATE tpzdb . mob_pools SET sJob = 1 WHERE familyid = 551;
UPDATE tpzdb . mob_pools SET namevis = 0 WHERE namevis = 1;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbDelay = 480 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 3 AND mJob = 2;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDelay = 360 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 3 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbSkill = 1 WHERE familyid = 176 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDelay = 360 WHERE familyid = 176 AND mJob = 13;
UPDATE tpzdb . mob_pools SET cmbDmgMult = 50 WHERE familyid = 176 AND mJob = 13;
UPDATE tpzdb . mob_pools SET rangedSkill = 0 WHERE familyid = 133 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 0 WHERE familyid = 327 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 0 WHERE familyid = 946 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 126 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 127 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 128 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 129 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 130 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 328 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 597 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 928 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 200 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 201 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 202 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 337 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 942 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 955 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 1 WHERE familyid = 115 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 1 WHERE familyid = 359 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 509 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 221 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 222 AND mJob = 11;
UPDATE tpzdb . mob_pools SET rangedSkill = 5 WHERE familyid = 223 AND mJob = 11;



